using System;
using System.Collections.Generic;
using System.Linq;
using MarkSmith.Core.Glox;

namespace MarkSmith.Core.Glox.Builder
{
    public class GloxLayoutDefinition
    {
        public string UniqueId { get; set; } = "urn:microsoft.com/office/officeart/2005/8/layout/custom1";
        public string Title { get; set; } = "Custom Layout";
        public string Desc { get; set; } = "Custom SmartArt layout generated by MarkSmith";
        public string Category { get; set; } = "process";
        public GloxLayoutNode RootNode { get; set; } = new GloxLayoutNode("diagram");
    }

    public class GloxLayoutNode
    {
        public string Name { get; set; }
        public GloxAlgorithm? Algorithm { get; set; }
        public GloxShape? Shape { get; set; }
        
        public List<GloxForEach> ForEachLoops { get; set; } = new();
        public List<GloxLayoutNode> Children { get; set; } = new();

        public GloxLayoutNode(string name)
        {
            Name = name;
        }

        public GloxLayoutNode SetAlgorithm(string type)
        {
            Algorithm = new GloxAlgorithm { Type = type };
            return this;
        }

        public GloxLayoutNode SetShape(string type)
        {
            Shape = new GloxShape { Type = type };
            return this;
        }

        public GloxLayoutNode AddForEach(string axis, string refNode, Action<GloxLayoutNode>? childConfig = null)
        {
            var fe = new GloxForEach { Axis = axis, RefNode = refNode };
            
            if (childConfig != null)
            {
                var child = new GloxLayoutNode(refNode);
                childConfig(child);
                Children.Add(child);
            }
            
            ForEachLoops.Add(fe);
            return this;
        }
        
        public GloxLayoutNode AddChild(string name, Action<GloxLayoutNode> config)
        {
            var child = new GloxLayoutNode(name);
            config(child);
            Children.Add(child);
            return this;
        }
    }

    public class GloxShape
    {
        public string Type { get; set; } = string.Empty;
    }

    public class GloxBuilder
    {
        private readonly GloxLayoutDefinition _def = new();

        public GloxBuilder WithMetadata(string uniqueId, string title, string desc, string category = "process")
        {
            _def.UniqueId = uniqueId;
            _def.Title = title;
            _def.Desc = desc;
            _def.Category = category;
            return this;
        }

        public GloxBuilder ConfigureRoot(Action<GloxLayoutNode> config)
        {
            config(_def.RootNode);
            return this;
        }

        public GloxLayoutDefinition Build()
        {
            return _def;
        }
    }
}
